/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Wrapper {

using System;
using System.Runtime.InteropServices;

class ClippingLibraryPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("ClippingLibrary", EntryPoint="SWIGRegisterExceptionCallbacks_ClippingLibrary")]
    public static extern void SWIGRegisterExceptionCallbacks_ClippingLibrary(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("ClippingLibrary", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_ClippingLibrary")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_ClippingLibrary(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_ClippingLibrary(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_ClippingLibrary(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(ClippingLibraryPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(ClippingLibraryPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("ClippingLibrary", EntryPoint="SWIGRegisterStringCallback_ClippingLibrary")]
    public static extern void SWIGRegisterStringCallback_ClippingLibrary(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_ClippingLibrary(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static ClippingLibraryPINVOKE() {
  }


  [DllImport("ClippingLibrary", EntryPoint="CSharp_new_Wrapper")]
  public static extern IntPtr new_Wrapper();

  [DllImport("ClippingLibrary", EntryPoint="CSharp_delete_Wrapper")]
  public static extern void delete_Wrapper(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_AddInnerRing")]
  public static extern void Wrapper_AddInnerRing(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_AddPoint")]
  public static extern void Wrapper_AddPoint(HandleRef jarg1, double jarg2, double jarg3);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_AddPolygon")]
  public static extern void Wrapper_AddPolygon(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_ExecuteDifference")]
  public static extern void Wrapper_ExecuteDifference(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_ExecuteIntersection")]
  public static extern void Wrapper_ExecuteIntersection(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_ExecuteUnion")]
  public static extern void Wrapper_ExecuteUnion(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_ExecuteXor")]
  public static extern void Wrapper_ExecuteXor(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_GetInnerRing")]
  public static extern bool Wrapper_GetInnerRing(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_GetPoint")]
  public static extern bool Wrapper_GetPoint(HandleRef jarg1, ref double jarg2, ref double jarg3);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_GetPolygon")]
  public static extern bool Wrapper_GetPolygon(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_InitializeClip")]
  public static extern void Wrapper_InitializeClip(HandleRef jarg1);

  [DllImport("ClippingLibrary", EntryPoint="CSharp_Wrapper_InitializeSubject")]
  public static extern void Wrapper_InitializeSubject(HandleRef jarg1);
}

}
